theme: jekyll-theme-minimal
title: Severin Vire
description: My Portfolio

url: "https://severinvire.github.io"
baseurl: "/svportfolio" 

defaults:
  - scope:
      path: ""
    values:
      title: "Severin Vire"

kramdown:
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock